create table if not exists public.seed_keywords (
  id uuid primary key default gen_random_uuid(),
  keyword text not null unique,
  category text,
  priority integer not null default 50,
  enabled boolean not null default true,
  source text not null default 'manual',
  parent_keyword_id uuid references public.seed_keywords(id) on delete set null,
  expires_at timestamptz,
  last_searched_at timestamptz,
  total_runs integer not null default 0,
  total_channels_added integer not null default 0,
  unique_channels_added integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists seed_keywords_active_idx
  on public.seed_keywords(enabled, last_searched_at asc nulls first, priority desc)
  where enabled = true;

create index if not exists seed_keywords_source_idx on public.seed_keywords(source);

create table if not exists public.keyword_discovery_log (
  id uuid primary key default gen_random_uuid(),
  ran_at timestamptz not null default now(),
  job text not null,
  candidates_found int not null default 0,
  candidates_added int not null default 0,
  metadata jsonb not null default '{}'
);

create index if not exists keyword_discovery_log_ran_at on
public.keyword_discovery_log(ran_at desc);

-- Initial 80 evergreen seed keywords
insert into public.seed_keywords (keyword, category, priority, source) values
  ('faceless finance', 'finance', 90, 'manual'),
  ('passive income ideas', 'finance', 90, 'manual'),
  ('ai automation business', 'finance', 85, 'manual'),
  ('cash cow youtube channel', 'finance', 85, 'manual'),
  ('side hustle 2026', 'finance', 80, 'manual'),
  ('dropshipping tutorial', 'finance', 75, 'manual'),
  ('stock market explained', 'finance', 80, 'manual'),
  ('crypto for beginners', 'finance', 75, 'manual'),
  ('personal finance tips', 'finance', 80, 'manual'),
  ('investing for beginners', 'finance', 80, 'manual'),
  ('ai tools', 'tech', 90, 'manual'),
  ('chatgpt tutorial', 'tech', 85, 'manual'),
  ('ai news today', 'tech', 85, 'manual'),
  ('claude ai tutorial', 'tech', 80, 'manual'),
  ('midjourney prompts', 'tech', 75, 'manual'),
  ('ai agents tutorial', 'tech', 80, 'manual'),
  ('ai for productivity', 'tech', 75, 'manual'),
  ('coding ai tools', 'tech', 75, 'manual'),
  ('llm explained', 'tech', 70, 'manual'),
  ('automation with ai', 'tech', 80, 'manual'),
  ('stoicism daily', 'lifestyle', 85, 'manual'),
  ('marcus aurelius wisdom', 'lifestyle', 80, 'manual'),
  ('stoic philosophy', 'lifestyle', 80, 'manual'),
  ('minimalism lifestyle', 'lifestyle', 75, 'manual'),
  ('discipline motivation', 'lifestyle', 75, 'manual'),
  ('mindset shift', 'lifestyle', 75, 'manual'),
  ('self improvement daily', 'lifestyle', 80, 'manual'),
  ('wisdom quotes', 'lifestyle', 70, 'manual'),
  ('history documentary', 'education', 80, 'manual'),
  ('ancient history facts', 'education', 75, 'manual'),
  ('medieval history', 'education', 75, 'manual'),
  ('roman empire facts', 'education', 75, 'manual'),
  ('world war 2 documentary', 'education', 75, 'manual'),
  ('historical mysteries', 'education', 75, 'manual'),
  ('lost civilizations', 'education', 70, 'manual'),
  ('space exploration', 'education', 75, 'manual'),
  ('quantum physics simple', 'education', 70, 'manual'),
  ('how things work', 'education', 75, 'manual'),
  ('science explained', 'education', 75, 'manual'),
  ('astronomy for beginners', 'education', 70, 'manual'),
  ('productivity tips', 'lifestyle', 80, 'manual'),
  ('time management', 'lifestyle', 75, 'manual'),
  ('deep work focus', 'lifestyle', 75, 'manual'),
  ('morning routine', 'lifestyle', 70, 'manual'),
  ('unsolved mysteries', 'entertainment', 75, 'manual'),
  ('true crime stories', 'entertainment', 75, 'manual'),
  ('cold case files', 'entertainment', 70, 'manual'),
  ('tech reviews 2026', 'tech', 75, 'manual'),
  ('iphone tips and tricks', 'tech', 70, 'manual'),
  ('android hidden features', 'tech', 70, 'manual'),
  ('best gadgets 2026', 'tech', 70, 'manual'),
  ('home workout no equipment', 'health', 75, 'manual'),
  ('calisthenics beginner', 'health', 70, 'manual'),
  ('weight loss tips', 'health', 75, 'manual'),
  ('healthy meal prep', 'health', 70, 'manual'),
  ('mental health tips', 'health', 75, 'manual'),
  ('easy recipes 5 minutes', 'lifestyle', 70, 'manual'),
  ('viral tiktok recipes', 'lifestyle', 70, 'manual'),
  ('budget meals', 'lifestyle', 70, 'manual'),
  ('minecraft tutorial', 'gaming', 70, 'manual'),
  ('fortnite tips 2026', 'gaming', 70, 'manual'),
  ('gaming setup tour', 'gaming', 65, 'manual'),
  ('motivational shorts', 'lifestyle', 80, 'manual'),
  ('finance shorts', 'finance', 80, 'manual'),
  ('history shorts', 'education', 75, 'manual'),
  ('science shorts', 'education', 75, 'manual'),
  ('stoic shorts', 'lifestyle', 80, 'manual'),
  ('luxury lifestyle shorts', 'lifestyle', 75, 'manual'),
  ('ai news shorts', 'tech', 80, 'manual'),
  ('weird history facts', 'entertainment', 75, 'manual'),
  ('mind blowing facts', 'entertainment', 75, 'manual'),
  ('did you know facts', 'entertainment', 70, 'manual'),
  ('billionaire mindset', 'finance', 75, 'manual'),
  ('luxury cars review', 'lifestyle', 65, 'manual'),
  ('chess strategy', 'gaming', 65, 'manual'),
  ('photography tutorial', 'education', 65, 'manual'),
  ('music theory basics', 'music', 60, 'manual'),
  ('travel vlog europe', 'lifestyle', 65, 'manual'),
  ('survival skills', 'education', 70, 'manual'),
  ('woodworking projects', 'education', 65, 'manual'),
  ('language learning hacks', 'education', 70, 'manual')
on conflict (keyword) do nothing;
